# Generated by Django 4.0.6 on 2022-07-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_scope_articlescope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlescope',
            name='is_main',
            field=models.BooleanField(),
        ),
    ]
